name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make

  macOS-build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
